- name: Mi primer playbook perro                ## Its a list
  connection: ansible.netcommon.network_cli     ## a Dictionary
  hosts: routers
  gather_facts: no
  tasks:                                         ## Dictionary 
    - name: Running remote commands to my NE
      cisco.ios.ios_command:
        commands:
#          - show ip interface brief | ex unas
          - show ip interface brief
#          - show running-config
  #        - show ip ospf neigh
      register: output

    - name: Print dog hector gil
      debug:
        var: output.stdout_lines



# [ 


# {
#   name='Mi Primer playbook perro',
#   connection='ansible.netcommon.network_cli',
#   hosts ='Internet1',
#   task=[
#           { name='run show version on remote devices',
#             cisco.ios.ios_command= {
#                                     commands='show version'
#                                     }
#           }
#         ]
# }


# ]
